/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package net.thauvin.erik.android.spellit;

public final class R {
    public static final class array {
        public static final int alphabet=0x7f040000;
        public static final int nato_alphabet=0x7f040001;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int about_text_fld=0x7f060000;
        public static final int main_entry_fld=0x7f060001;
        public static final int main_result_fld=0x7f060003;
        public static final int main_spell_btn=0x7f060002;
        public static final int main_tap_lbl=0x7f060004;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class string {
        public static final int about_menu_txt=0x7f050009;
        public static final int about_txt=0x7f050008;
        public static final int alert_dialog_cancel=0x7f05000b;
        public static final int alert_dialog_ok=0x7f05000a;
        public static final int app_name=0x7f050000;
        public static final int as_in_txt=0x7f05000c;
        public static final int done_txt=0x7f05000e;
        public static final int main_entry_err_txt=0x7f050005;
        public static final int main_entry_hint_txt=0x7f050004;
        public static final int main_spell_btn_txt=0x7f050001;
        public static final int main_tap_lbl_repeat_txt=0x7f050003;
        public static final int main_tap_lbl_txt=0x7f050002;
        public static final int nato_menu_txt=0x7f050006;
        public static final int sample_txt=0x7f050007;
        public static final int space_txt=0x7f05000d;
    }
}
